version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/SkredvarselGarminWeb"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/SkredvarselGarminWeb/SkredvarselGarminWeb/Frontend"
    schedule:
      interval: "weekly"
