version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/SkredvarselGarminWeb"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/SkredvarselGarminWeb"
    schedule:
      interval: "weekly"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/SkredvarselGarminWeb/SkredvarselGarminWeb/Frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
