# fly.toml app configuration file generated for skredvarsel-garmin-web-prod on 2023-04-27T20:54:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skredvarsel-garmin-web-prod"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  strategy = "rolling"

[env]
  PRIMARY_REGION = "arn"

[[mounts]]
  source = "skredvarselGarmin_data_machines"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "5s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
    method = "get"
    path = "/healthz"
    protocol = "http"
